spring.application.name=customerservice
spring.data.mongodb.uri=mongodb+srv://sanidhyam2005:sani%4005@cluster0.rqpptyr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=ecom_app
server.port=8087









